[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
yieldcash = "8Xr5vvjshTFqVtkMzrWNV2ZCw4pKqxNdoir1B1KdrNWR"

[programs.devnet]
yieldcash = "8Xr5vvjshTFqVtkMzrWNV2ZCw4pKqxNdoir1B1KdrNWR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=0e894b68-bfe8-4dca-825e-6bca69cda266"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha --require tsx --extension ts --timeout 1000000 \"tests/**/*.ts\""
