# Node 2 Configuration (Validator)

[network]
listen_address = "/ip4/127.0.0.1/tcp/9002"
bootstrap_nodes = [
    "/ip4/127.0.0.1/tcp/9001/p2p/12D3KooWNvs13kVoSGHeu6x5jC3kKijSfTk9ZeSyMC3CXfu4MLQt"
]
enable_mdns = true

[node]
node_type = "ResourceProvider"
max_cpu_usage = 80
max_memory_usage = 70
max_storage_usage = 10240

[storage]
data_dir = "./data/node2"
