[toolchain]
package_manager = "yarn"
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
shadow_fence = "6vgnGzWH7vGT8z8tfMRw2Va2qQiY7SmmHBHB3PphGu5S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
