[features]
resolution = true
skip-lint = false

[programs.localnet]
solvoid_zk = "Fg6PaFpoGXkYsidMpSsu3SWJYEHp7rQU9YSTFNDQ4F5i"

[programs.devnet]
solvoid_zk = "Fg6PaFpoGXkYsidMpSsu3SWJYEHp7rQU9YSTFNDQ4F5i"

[programs.mainnet]
solvoid_zk = "Fg6PaFpoGXkYsidMpSsu3SWJYEHp7rQU9YSTFNDQ4F5i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy-local = "anchor build && anchor deploy --provider.cluster localnet"
deploy-devnet = "anchor build && anchor deploy --provider.cluster devnet"
deploy-mainnet = "anchor build && anchor deploy --provider.cluster mainnet"
