[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
wavis_success = "GjWUevQsr5QLWxRzXNpVCZKkQmjEdjijEA65JujZ2HXS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ruka/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
